[package]
name = "wdl-grammar"
version = "0.3.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition.workspace = true
license.workspace = true
description = "A parse tree for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-grammar"

[dependencies]
clap = { workspace = true, optional = true }
colored = { workspace = true, optional = true }
convert_case.workspace = true
env_logger = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
log = { workspace = true, optional = true }
nonempty.workspace = true
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
logos = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
rowan = { workspace = true }
wdl-core = { path = "../wdl-core", version = "0.2.0" }
wdl-macros = { path = "../wdl-macros", version = "0.1.0" }

[dev-dependencies]
pretty_assertions = { workspace = true }
miette = { workspace = true, features = ["fancy"]}
rayon = { workspace = true }
colored = { workspace = true }

[features]
binaries = [
    "dep:clap",
    "dep:colored",
    "dep:env_logger",
    "dep:indexmap",
    "dep:log",
    "dep:serde",
    "dep:serde_with",
    "dep:tokio",
    "dep:toml",
]
experimental = []

[[bin]]
name = "wdl-grammar"
path = "src/main.rs"
required-features = ["binaries"]

[[test]]
name = "parsing"
harness = false
