[package]
name = "wdl-grammar"
version = "0.1.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition.workspace = true
license.workspace = true
description = "Grammar lexing and parsing for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-grammar"

[dependencies]
clap = { workspace = true, optional = true }
colored = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
log = { workspace = true, optional = true }
nonempty.workspace = true
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
wdl-core = { path = "../wdl-core" }
wdl-macros = { path = "../wdl-macros" }

[features]
binaries = [
    "dep:clap",
    "dep:colored",
    "dep:env_logger",
    "dep:indexmap",
    "dep:log",
    "dep:serde",
    "dep:serde_with",
    "dep:tokio",
    "dep:toml",
]

[[bin]]
name = "wdl-grammar"
path = "src/main.rs"
required-features = ["binaries"]
