[package]
name = "wdl-grammar"
version = "0.13.0"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
description = "A parse tree for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-grammar"

[dependencies]
codespan-reporting = { workspace = true, optional = true }
itertools = { workspace = true }
logos = { workspace = true }
rowan = { workspace = true }
strum = { version = "0.27", features = ["derive"] }

[dev-dependencies]
codespan-reporting = { workspace = true }
colored = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }

[features]
codespan = ["dep:codespan-reporting"]

[lints]
workspace = true

[[test]]
name = "parsing"
required-features = ["codespan"]
harness = false
