[package]
name = "wdl-ast"
version = "0.3.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition.workspace = true
license.workspace = true
description = "An abstract syntax tree for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-ast"

[dependencies]
wdl-grammar = { path = "../wdl-grammar", version = "0.4.0" }
rowan = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
approx = { workspace = true }
rayon = { workspace = true }
colored = { workspace = true }
codespan-reporting = { workspace = true }

[features]
codespan = ["wdl-grammar/codespan"]

[[test]]
name = "validation"
required-features = ["codespan"]
harness = false
