[package]
name = "wdl-engine"
version = "0.1.0"
rust-version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution engine for Workflow Description Language (WDL) documents."
documentation = "https://docs.rs/wdl-engine"

[dependencies]
wdl-grammar = { version = "0.11.0", path = "../wdl-grammar" }
wdl-ast = { version = "0.10.0", path = "../wdl-ast" }
wdl-analysis = { version = "0.6.0", path = "../wdl-analysis" }
anyhow = { workspace = true }
ordered-float = { workspace = true }
indexmap = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
tempfile = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
petgraph = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
sysinfo = { workspace = true }
rowan = { workspace = true }
crankshaft = { workspace = true }
rand = { workspace = true }
tokio-util = { workspace = true }
nonempty = { workspace = true }
path-clean = { workspace = true }
url = { workspace = true }
http-cache-stream-reqwest = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
dirs = { workspace =  true }

[dev-dependencies]
pretty_assertions = { workspace = true }
codespan-reporting = { workspace = true }
colored = { workspace = true }
approx = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }

[lints]
workspace = true

[features]
default = []
codespan = ["wdl-ast/codespan"]

[[test]]
name = "inputs"
required-features = ["codespan"]
harness = false

[[test]]
name = "tasks"
required-features = ["codespan"]
harness = false

[[test]]
name = "workflows"
required-features = ["codespan"]
harness = false
