# wdl-engine configuration for the St Jude Slurm HPC, appropriate for use with the
# `SPROCKET_TEST_ENGINE_CONFIG` environment variable.
backends.default.type = "slurm_apptainer"
backends.default.default_slurm_partition.name = "gpu"
backends.default.default_slurm_partition.max_cpu_per_task = 4
backends.default.default_slurm_partition.max_memory_per_task = "16 GiB"
backends.default.extra_sbatch_args = ["--time=1"]
backends.default.max_scatter_concurrency = 200
experimental_features_enabled = true
