[package]
name = "wdl-doc"
version = "0.3.2"
description = "Documentation generator for Workflow Description Language (WDL) documents."
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wdl-analysis = { path = "../wdl-analysis", version = "0.8.2" }
wdl-ast = { path = "../wdl-ast", version = "0.12.1" }

ammonia.workspace = true
anyhow.workspace = true
indexmap.workspace = true
maud.workspace = true
pathdiff.workspace = true
pulldown-cmark.workspace = true
tokio.workspace = true

[lints]
workspace = true

[[test]]
name = "doc"
harness = false
