[package]
name = "wdl-format"
version = "0.6.1"
description = "Formatting of WDL (Workflow Description Language) documents"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
wdl-ast = { path = "../wdl-ast", version = "0.12.1", features = ["codespan"] }

nonempty.workspace = true

[dev-dependencies]
approx = { workspace = true }
codespan-reporting = { workspace = true }
colored = { workspace = true }
pretty_assertions.workspace = true
rayon = { workspace = true }

[lints]
workspace = true

[[test]]
name = "format"
harness = false
