[package]
name = "wdl"
version = "0.4.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
license.workspace = true
edition.workspace = true
description = "Lexing, parsing, validation, and linting for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl"
readme = "../README.md"

[dependencies]
wdl-grammar = { path = "../wdl-grammar", version = "0.4.0", optional = true }
wdl-ast = { path = "../wdl-ast", version = "0.3.0", optional = true }
wdl-lint = { path = "../wdl-lint", version = "0.2.0", optional = true }
clap = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
colored = { workspace = true, optional = true }
codespan-reporting = { workspace = true, optional = true }

[dev-dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
codespan-reporting = { workspace = true }

[features]
default = ["ast", "grammar", "lint"]
ast = ["dep:wdl-ast"]
grammar = ["dep:wdl-grammar"]
lint = ["dep:wdl-lint"]
codespan = ["ast", "wdl-ast/codespan", "dep:codespan-reporting"]
binaries = ["codespan", "lint", "dep:clap", "dep:anyhow", "dep:colored"]

[[example]]
name = "explore"
required-features = ["codespan"]

[[example]]
name = "parse"
required-features = ["codespan"]

[[bin]]
name = "wdl"
required-features = ["binaries"]

[package.metadata.docs.rs]
all-features = true
