[package]
name = "wdl"
version = "0.7.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
rust-version.workspace = true
license.workspace = true
edition.workspace = true
description = "Lexing, parsing, validation, and linting for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl"
readme = "../README.md"

[dependencies]
wdl-grammar = { path = "../wdl-grammar", version = "0.7.0", optional = true }
wdl-ast = { path = "../wdl-ast", version = "0.6.0", optional = true }
wdl-lint = { path = "../wdl-lint", version = "0.5.0", optional = true }
wdl-analysis = { path = "../wdl-analysis", version = "0.2.0", optional = true }
wdl-lsp = { path = "../wdl-lsp", version = "0.2.0", optional = true }
tracing-subscriber = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
colored = { workspace = true, optional = true }
codespan-reporting = { workspace = true, optional = true }
indicatif = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
codespan-reporting = { workspace = true }

[features]
default = ["analysis", "ast", "grammar", "lint"]
analysis = ["dep:wdl-analysis"]
ast = ["dep:wdl-ast"]
grammar = ["dep:wdl-grammar"]
lint = ["dep:wdl-lint"]
lsp = ["dep:wdl-lsp"]
codespan = ["ast", "wdl-ast/codespan", "dep:codespan-reporting"]
cli = [
    "analysis",
    "codespan",
    "lint",
    "dep:clap",
    "dep:tracing-subscriber",
    "dep:anyhow",
    "dep:colored",
    "dep:indicatif",
    "dep:tokio",
]

[[example]]
name = "explore"
required-features = ["codespan"]

[[example]]
name = "parse"
required-features = ["codespan"]

[[bin]]
name = "wdl"
required-features = ["cli"]

[package.metadata.docs.rs]
all-features = true
