[package]
name = "wdl"
version.workspace = true
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
license.workspace = true
edition.workspace = true
description = "Lexing, parsing, validation, and linting for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl"
readme = "../README.md"

[dependencies]
wdl-ast = { path = "../wdl-ast", version = "0.1.0", optional = true }
wdl-core = { path = "../wdl-core", version = "0.2.0", optional = true }
wdl-grammar = { path = "../wdl-grammar", version = "0.3.0", optional = true }

[features]
default = []
ast = ["dep:wdl-ast"]
core = ["dep:wdl-core"]
grammar = ["dep:wdl-grammar"]

[[example]]
name = "wdl_explore"
required-features = ["ast", "grammar"]

[[example]]
name = "wdl_parse"
required-features = ["ast", "grammar"]

[package.metadata.docs.rs]
all-features = true
