[package]
name = "wdl-cli"
version = "0.0.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wdl-analysis = { path = "../wdl-analysis", version = "0.7.0" }
wdl-ast = { path = "../wdl-ast", version = "0.11.0" }
wdl-engine = { path = "../wdl-engine", version = "0.2.0" }
wdl-lint = { path = "../wdl-lint", version = "0.10.0" }

anyhow.workspace = true
codespan-reporting.workspace = true
futures.workspace = true
indexmap.workspace = true
nonempty.workspace = true
path-clean.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
shellexpand.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
