[package]
name = "wdl-lint"
version = "0.3.0"
description = "Lint rules for Workflow Description Language (WDL) documents"
authors.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/wdl-lint"
readme = "../README.md"

[dependencies]
wdl-ast = { path = "../wdl-ast", version = "0.5.0" }
convert_case = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
codespan-reporting = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }
colored = { workspace = true }

[features]
codespan = ["wdl-ast/codespan"]

[[test]]
name = "lints"
required-features = ["codespan"]
harness = false
