[package]
name = "wdl-diagnostics"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
codespan-reporting.workspace = true
serde.workspace = true
wdl-ast = { path = "../wdl-ast", version = "0.21.1" }
wdl-engine = { path = "../wdl-engine", version = "0.12.0", optional = true }

[features]
backtrace = ["dep:wdl-engine"]

[lints]
workspace = true
