version = "v1"

[repositories."ENCODE-DCC/chip-seq-pipeline2"]
identifier = "ENCODE-DCC/chip-seq-pipeline2"
commit_hash = "26eeda81a0540dc793fc69b0c390d232ca7ca50a"

[repositories."getwilds/ww-fastq-to-cram"]
identifier = "getwilds/ww-fastq-to-cram"
commit_hash = "7dd6c4c7c8c9fc6dcd4eb5ff8f3262cd26d5e7cc"

[repositories."stjudecloud/workflows"]
identifier = "stjudecloud/workflows"
commit_hash = "08e3d49c7fb10086fe516feb2f400c1d65ef6100"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (10:25)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (68:66)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W003::[Completeness]::Medium] missing parameter meta within task: files (5:6-5:23)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W003::[Completeness]::Medium] missing parameter meta within task: labels (4:6-4:26)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W003::[Completeness]::Medium] missing parameter meta within task: ref_files (6:6-6:27)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (84:45-84:56)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (85:46-85:65)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (86:26-86:39)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (87:39-87:52)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (91:18-91:27)"

[[concerns]]
kind = "LintWarning"
document = "ENCODE-DCC/chip-seq-pipeline2:/dev/test/test_task/compare_md5sum.wdl"
message = "[v1::W012::[Style, Clarity]::Low] string defined with single quotes (93:17-93:36)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (133:46)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (182:63)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (34:105)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (57:13)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W001::[Spacing, Style]::Low] trailing space (8:42)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within task: crai (203:5-203:9)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within task: cram (202:5-202:9)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within task: unmapped_bam (129:5-129:17)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within task: validation (165:5-165:15)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within workflow: unmapped_cram_indexes (75:5-75:26)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within workflow: unmapped_crams (74:5-74:19)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W003::[Completeness]::Medium] extraneous parameter meta within workflow: validation (76:5-76:15)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (134:6-134:18)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (170:6-170:21)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (23:10-23:36)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (83:6-83:24)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W007::[Spacing, Style]::Low] missing newline at the end of the file (205:2-205:2)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W010::[Style]::Low] double pound signs are reserved for preamble comments (21:1-21:25)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W010::[Style]::Low] double pound signs are reserved for preamble comments (5:1-5:24)"

[[concerns]]
kind = "LintWarning"
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "[v1::W010::[Style]::Low] double pound signs are reserved for preamble comments (80:1-80:22)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (32:12-32:14)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (33:13-33:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (34:13-34:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (35:13-35:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (36:13-36:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (37:13-37:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (38:13-38:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (39:13-39:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (40:13-40:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (41:10-41:12)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (42:13-42:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (43:13-43:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (44:13-44:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (45:13-45:15)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (107:14-107:23)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (108:14-108:29)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (249:14-249:23)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (250:14-250:29)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (552:13-552:34)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (553:13-553:34)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (555:13-555:28)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (556:13-556:29)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (564:13-564:27)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (565:13-565:27)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (597:13-597:40)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (61:13-61:36)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (62:13-62:31)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (818:9-818:30)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (819:9-819:30)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/star.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (820:9-820:30)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/tools/util.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (413:14-413:21)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (101:15-101:24)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (102:15-102:30)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (40:16-40:29)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (41:16-41:30)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (42:17-42:36)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (43:17-43:37)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/reference/make-qc-reference.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (125:14-125:21)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-core.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (138:13-138:40)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-variant-calling.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (42:14-42:23)"

[[concerns]]
kind = "LintWarning"
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-variant-calling.wdl"
message = "[v1::W006::[Naming, Style, Clarity]::Medium] identifier must be snake case (43:14-43:29)"
