[workspace]
members = [
    "wdl",
    "wdl-ast",
    "wdl-core",
    "wdl-gauntlet",
    "wdl-grammar",
    "wdl-macros",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.2.0"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.4"
env_logger = "0.10.0"
indexmap = { version = "2.1.0", features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.20"
nonempty = { version = "0.9.0", features = ["serialize"] }
ordered-float = "4.2.0"
pest = { version = "2.7.5", features = ["pretty-print"] }
pest_derive = "2.7.5"
regex = "1.10.2"
serde = { version = "1", features = ["derive"] }
serde_with = "3.4.0"
tokio = { version = "1.33.0", features = ["full"] }
toml = "0.8.8"
