[workspace]
members = ["wdl-grammar"]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
env_logger = "0.10.0"
indexmap = { version = "2.1.0", features = ["serde"] }
log = "0.4.20"
pest = { version = "2.7.5", features = ["pretty-print"] }
pest_derive = "2.7.5"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3.4.0" }
toml = "0.8.8"
