name: Generate site preview
on:
  push:
    branches:
      - doc-search
  workflow_dispatch:
# TODO: Remove this before merge
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - uses: actions/setup-node@v4
      - name: Generate site
        run: |
          cargo run -p sprocket -- dev doc ./crates/wdl-doc/tests/ui/base/assets --output ./crates/wdl-doc/doc
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: crates/wdl-doc/doc/
          branch: gh-pages
          target-folder: "doc-search-test"
          clean: true
